import cookie from "@fastify/cookie";
import cors from "@fastify/cors";
import helmet from "@fastify/helmet";
import jwt from "@fastify/jwt";
import rateLimit from "@fastify/rate-limit";
import Fastify from "fastify";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { audit } from "./audit.js";
import { requireAuth, requireRole, hashPassword, verifyPassword } from "./auth.js";
import { config } from "./config.js";
import { db } from "./database.js";
import { publish, subscribe } from "./events.js";
import { registerPhaseTwoRoutes } from "./phase2.js";
import { registerPhaseThreeRoutes } from "./phase3.js";

const registerSchema = z.object({ organizationName: z.string().min(2).max(120), organizationSlug: z.string().regex(/^[a-z0-9-]{2,64}$/), name: z.string().min(2).max(120), email: z.string().email(), password: z.string().min(12).max(128) });
const loginSchema = z.object({ email: z.string().email(), password: z.string().min(1) });
const createUserSchema = z.object({ name: z.string().min(2).max(120), email: z.string().email(), password: z.string().min(12).max(128), role: z.enum(["OPERATIONS_COORDINATOR", "VIEWER"]).default("VIEWER") });
const assetTypeSchema = z.enum(["FPSO", "FIXED_PLATFORM", "DRILLING_RIG", "SEMI_SUBMERSIBLE", "JACKUP", "WIND_FARM", "SUBSEA_FIELD", "TERMINAL", "PORT_BASE", "OTHER"]);
const assetStatusSchema = z.enum(["PLANNED", "ACTIVE", "MAINTENANCE", "INACTIVE", "DECOMMISSIONED"]);
const assetSchema = z.object({ name: z.string().min(2).max(120), code: z.string().regex(/^[A-Z0-9-]{2,32}$/), type: assetTypeSchema, status: assetStatusSchema.default("PLANNED"), latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), timezone: z.string().min(1).max(64).default("UTC"), operator: z.string().max(120).optional(), description: z.string().max(4000).optional(), metadata: z.record(z.string(), z.unknown()).default({}) });
const updateAssetSchema = assetSchema.partial();
const assetAreaSchema = z.object({ assetId: z.string().uuid(), parentId: z.string().uuid().optional(), name: z.string().min(2).max(120), code: z.string().regex(/^[A-Z0-9-]{2,32}$/), type: z.string().min(2).max(80), description: z.string().max(4000).optional() });
const equipmentSchema = z.object({ assetId: z.string().uuid(), areaId: z.string().uuid().optional(), name: z.string().min(2).max(120), code: z.string().regex(/^[A-Z0-9-]{2,32}$/), type: z.string().min(2).max(80), status: z.enum(["AVAILABLE", "IN_USE", "MAINTENANCE", "UNAVAILABLE", "RETIRED"]).default("AVAILABLE"), criticality: z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]).default("MEDIUM"), manufacturer: z.string().max(120).optional(), model: z.string().max(120).optional(), metadata: z.record(z.string(), z.unknown()).default({}) });
const updateAssetAreaSchema = assetAreaSchema.omit({ assetId: true, parentId: true }).partial();
const updateEquipmentSchema = equipmentSchema.omit({ assetId: true, areaId: true }).partial();
const operationalWindowSchema = z.object({ assetId: z.string().uuid(), name: z.string().min(2).max(160), type: z.string().min(2).max(80), startAt: z.string().datetime(), endAt: z.string().datetime(), constraints: z.record(z.string(), z.unknown()).default({}), status: z.enum(["OPEN", "CLOSED", "CONSTRAINED"]).default("OPEN") }).refine((value) => new Date(value.endAt) > new Date(value.startAt), { message: "endAt must be after startAt", path: ["endAt"] });

export function buildApp() {
  const app = Fastify({ logger: { level: process.env.LOG_LEVEL ?? "info" }, genReqId: () => randomUUID() });
  app.register(helmet, { contentSecurityPolicy: false });
  app.register(cors, { origin: config.WEB_ORIGIN, credentials: true });
  app.register(cookie);
  app.register(jwt, { secret: config.JWT_SECRET, cookie: { cookieName: "ocean_session", signed: false } });
  app.register(rateLimit, { max: 100, timeWindow: "1 minute" });
  registerPhaseTwoRoutes(app);
  registerPhaseThreeRoutes(app);

  app.get("/health", async () => ({ status: "ok" }));
  app.get("/ready", async (_request, reply) => { try { await db().query("SELECT 1"); return { status: "ready", database: "available" }; } catch { return reply.code(503).send({ status: "not_ready", database: "unavailable" }); } });
  app.get("/api/v1/events", async (request, reply) => { const claims = await requireAuth(request); reply.hijack(); reply.raw.writeHead(200, { "Content-Type": "text/event-stream", "Cache-Control": "no-cache, no-transform", Connection: "keep-alive" }); const send = (event: { id: string; type: string; payload: object; occurredAt: string }) => reply.raw.write(`id: ${event.id}\nevent: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`); reply.raw.write(": connected\n\n"); const heartbeat = setInterval(() => reply.raw.write(": heartbeat\n\n"), 25000); const unsubscribe = subscribe(claims.organizationId, send); request.raw.on("close", () => { clearInterval(heartbeat); unsubscribe(); }); });
  app.get("/api/v1/assets/:id/weather", async (request, reply) => { const claims = await requireAuth(request); const assetId = (request.params as { id: string }).id; const result = await db().query("SELECT w.* FROM weather_observations w JOIN offshore_assets a ON a.id=w.asset_id WHERE w.asset_id=$1 AND a.organization_id=$2 ORDER BY w.observed_at DESC LIMIT 48", [assetId, claims.organizationId]); if (!result.rows.length) { const exists = await db().query("SELECT 1 FROM offshore_assets WHERE id=$1 AND organization_id=$2", [assetId, claims.organizationId]); if (!exists.rows[0]) return reply.code(404).send({ message: "Asset not found" }); } return { data: result.rows, dataMode: "SIMULATED" }; });
  app.get("/api/v1/assets/:id/weather/forecast", async (request, reply) => { const claims = await requireAuth(request); const assetId = (request.params as { id: string }).id; const result = await db().query("SELECT f.* FROM weather_forecasts f JOIN offshore_assets a ON a.id=f.asset_id WHERE f.asset_id=$1 AND a.organization_id=$2 AND f.valid_at >= now() - interval '1 hour' ORDER BY f.valid_at LIMIT 48", [assetId, claims.organizationId]); if (!result.rows.length) { const exists = await db().query("SELECT 1 FROM offshore_assets WHERE id=$1 AND organization_id=$2", [assetId, claims.organizationId]); if (!exists.rows[0]) return reply.code(404).send({ message: "Asset not found" }); } return { data: result.rows, dataMode: "SIMULATED" }; });
  app.get("/api/v1/assets/:id/weather/impact", async (request, reply) => { const claims = await requireAuth(request); const assetId = (request.params as { id: string }).id; const asset = await db().query("SELECT id FROM offshore_assets WHERE id=$1 AND organization_id=$2", [assetId, claims.organizationId]); if (!asset.rows[0]) return reply.code(404).send({ message: "Asset not found" }); const latest = await db().query("SELECT * FROM weather_observations WHERE asset_id=$1 ORDER BY observed_at DESC LIMIT 1", [assetId]); const observation = latest.rows[0] as { wind_speed: number; wave_height: number } | undefined; const hazardous = Boolean(observation && (Number(observation.wind_speed) > 16 || Number(observation.wave_height) > 2.5)); const activities = await db().query("SELECT id,title,status,planned_start,planned_end FROM operational_activities WHERE organization_id=$1 AND asset_id=$2 AND status IN ('PLANNED','APPROVED','READY','IN_PROGRESS','PAUSED','BLOCKED','DELAYED') AND planned_end >= now() AND planned_start <= now() + interval '24 hours' ORDER BY planned_start", [claims.organizationId, assetId]); return { dataMode: "SIMULATED", hazardous, limits: { maxWindSpeed: 16, maxWaveHeight: 2.5 }, observation: observation ?? null, affectedActivities: hazardous ? activities.rows : [] }; });
  app.post("/api/v1/simulator/assets/:id/weather", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR", "OPERATIONS_COORDINATOR"]); const assetId = (request.params as { id: string }).id; const asset = await db().query("SELECT id FROM offshore_assets WHERE id=$1 AND organization_id=$2", [assetId, claims.organizationId]); if (!asset.rows[0]) return reply.code(404).send({ message: "Asset not found" }); const id = randomUUID(), wind = Number((8 + Math.random() * 12).toFixed(1)), wave = Number((.5 + Math.random() * 2.5).toFixed(1)); const result = await db().query("INSERT INTO weather_observations (id,asset_id,wind_speed,wave_height,visibility,source,metadata) VALUES ($1,$2,$3,$4,10,'SIMULATOR','{\"dataMode\":\"SIMULATED\"}') RETURNING *", [id, assetId, wind, wave]); const hazardous = wind > 16 || wave > 2.5; const affected = hazardous ? await db().query("SELECT id,title,status,planned_start,planned_end FROM operational_activities WHERE organization_id=$1 AND asset_id=$2 AND status IN ('PLANNED','APPROVED','READY','IN_PROGRESS','PAUSED','BLOCKED','DELAYED') AND planned_end >= now() AND planned_start <= now() + interval '24 hours' ORDER BY planned_start", [claims.organizationId, assetId]) : { rows: [] as object[] }; let alertId: string | undefined; if (hazardous) { alertId = randomUUID(); await db().query("INSERT INTO alerts (id,organization_id,entity_type,entity_id,title,message,severity,metadata) VALUES ($1,$2,'OffshoreAsset',$3,'Meteocean limit exceeded',$4,'HIGH',$5)", [alertId, claims.organizationId, assetId, `Simulated conditions: wind ${wind} kn, waves ${wave} m.`, JSON.stringify({ weatherObservationId: id, affectedActivityIds: affected.rows.map((activity) => (activity as { id: string }).id), dataMode: "SIMULATED" })]); publish({ id: alertId, organizationId: claims.organizationId, type: "alert.created", payload: { assetId, weatherObservationId: id, dataMode: "SIMULATED" }, occurredAt: new Date().toISOString() }); } await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "weather.observed", entityType: "WeatherObservation", entityId: id, newValue: result.rows[0], ipAddress: request.ip, correlationId: request.id }); publish({ id, organizationId: claims.organizationId, type: "weather.observed", payload: { assetId, hazardous, dataMode: "SIMULATED" }, occurredAt: new Date().toISOString() }); return reply.code(201).send({ ...result.rows[0], alertCreated: hazardous, affectedActivities: affected.rows, dataMode: "SIMULATED" }); });
  app.post("/api/v1/simulator/assets/:id/weather/forecast", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR", "OPERATIONS_COORDINATOR"]); const assetId = (request.params as { id: string }).id; const asset = await db().query("SELECT id FROM offshore_assets WHERE id=$1 AND organization_id=$2", [assetId, claims.organizationId]); if (!asset.rows[0]) return reply.code(404).send({ message: "Asset not found" }); const forecastAt = new Date(); const rows = await Promise.all(Array.from({ length: 6 }, async (_, index) => { const id = randomUUID(); const wind = Number((9 + Math.random() * 10).toFixed(1)); const wave = Number((.6 + Math.random() * 2.2).toFixed(1)); const validAt = new Date(forecastAt.getTime() + (index + 1) * 60 * 60 * 1000).toISOString(); return (await db().query("INSERT INTO weather_forecasts (id,asset_id,forecast_at,valid_at,wind_speed,wave_height,visibility,source,confidence,metadata) VALUES ($1,$2,$3,$4,$5,$6,10,'SIMULATOR',0.8,'{\"dataMode\":\"SIMULATED\"}') RETURNING *", [id, assetId, forecastAt.toISOString(), validAt, wind, wave])).rows[0]; })); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "weather.forecast_generated", entityType: "WeatherForecast", entityId: rows[0].id, newValue: { assetId, forecasts: rows.length, dataMode: "SIMULATED" }, ipAddress: request.ip, correlationId: request.id }); publish({ id: randomUUID(), organizationId: claims.organizationId, type: "weather.forecast_updated", payload: { assetId, count: rows.length, dataMode: "SIMULATED" }, occurredAt: new Date().toISOString() }); return reply.code(201).send({ data: rows, dataMode: "SIMULATED" }); });
  app.get("/api/v1/operational-windows", async (request) => { const claims = await requireAuth(request); const { assetId } = request.query as { assetId?: string }; const result = await db().query(`SELECT w.* FROM operational_windows w WHERE w.organization_id=$1 ${assetId ? "AND w.asset_id=$2" : ""} ORDER BY w.start_at`, assetId ? [claims.organizationId, assetId] : [claims.organizationId]); return { data: result.rows, dataMode: "SIMULATED" }; });
  app.post("/api/v1/operational-windows", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR", "OPERATIONS_COORDINATOR"]); const body = operationalWindowSchema.parse(request.body); const asset = await db().query("SELECT id FROM offshore_assets WHERE id=$1 AND organization_id=$2", [body.assetId, claims.organizationId]); if (!asset.rows[0]) return reply.code(404).send({ message: "Asset not found" }); const id = randomUUID(); const result = await db().query("INSERT INTO operational_windows (id,organization_id,asset_id,name,type,start_at,end_at,constraints,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *", [id, claims.organizationId, body.assetId, body.name, body.type, body.startAt, body.endAt, JSON.stringify({ ...body.constraints, dataMode: "SIMULATED" }), body.status]); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "operational_window.created", entityType: "OperationalWindow", entityId: id, newValue: result.rows[0], ipAddress: request.ip, correlationId: request.id }); publish({ id, organizationId: claims.organizationId, type: "operational_window.created", payload: { assetId: body.assetId, status: body.status, dataMode: "SIMULATED" }, occurredAt: new Date().toISOString() }); return reply.code(201).send({ ...result.rows[0], dataMode: "SIMULATED" }); });

  app.post("/api/v1/auth/register", { config: { rateLimit: { max: 5, timeWindow: "1 minute" } } }, async (request, reply) => {
    const body = registerSchema.parse(request.body); const organizationId = randomUUID(); const userId = randomUUID(); const client = await db().connect();
    try { await client.query("BEGIN"); await client.query("INSERT INTO organizations (id,name,slug,timezone) VALUES ($1,$2,$3,'UTC')", [organizationId, body.organizationName, body.organizationSlug]); await client.query("INSERT INTO users (id,organization_id,name,email,password_hash,status) VALUES ($1,$2,$3,$4,$5,'ACTIVE')", [userId, organizationId, body.name, body.email.toLowerCase(), await hashPassword(body.password)]); await client.query("INSERT INTO roles (id,organization_id,name,system_role) VALUES ($1,$2,'Administrator','ADMINISTRATOR')", [randomUUID(), organizationId]); await client.query("INSERT INTO user_roles (user_id,role_id) SELECT $1,id FROM roles WHERE organization_id=$2 AND system_role='ADMINISTRATOR'", [userId, organizationId]); await client.query("COMMIT"); } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
    await audit({ organizationId, userId, action: "organization.created", entityType: "Organization", entityId: organizationId, newValue: { name: body.organizationName }, ipAddress: request.ip, correlationId: request.id });
    const token = await reply.jwtSign({ sub: userId, organizationId, email: body.email.toLowerCase(), roles: ["ADMINISTRATOR"] }, { expiresIn: "15m" }); reply.setCookie("ocean_session", token, { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", path: "/", maxAge: 900 }); return reply.code(201).send({ user: { id: userId, name: body.name, email: body.email, roles: ["ADMINISTRATOR"] }, organization: { id: organizationId, name: body.organizationName } });
  });
  app.post("/api/v1/auth/login", { config: { rateLimit: { max: 5, timeWindow: "1 minute" } } }, async (request, reply) => { const body = loginSchema.parse(request.body); const result = await db().query("SELECT u.id,u.organization_id,u.name,u.email,u.password_hash,array_agg(r.system_role) roles FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.email=$1 AND u.status='ACTIVE' GROUP BY u.id", [body.email.toLowerCase()]); const user = result.rows[0] as { id: string; organization_id: string; name: string; email: string; password_hash: string; roles: string[] } | undefined; if (!user || !(await verifyPassword(user.password_hash, body.password))) return reply.code(401).send({ message: "Invalid credentials" }); const token = await reply.jwtSign({ sub: user.id, organizationId: user.organization_id, email: user.email, roles: user.roles }, { expiresIn: "15m" }); reply.setCookie("ocean_session", token, { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", path: "/", maxAge: 900 }); await audit({ organizationId: user.organization_id, userId: user.id, action: "auth.login", entityType: "User", entityId: user.id, ipAddress: request.ip, correlationId: request.id }); return { user: { id: user.id, name: user.name, email: user.email, roles: user.roles } }; });
  app.post("/api/v1/auth/logout", async (request, reply) => { const claims = await requireAuth(request); reply.clearCookie("ocean_session", { path: "/" }); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "auth.logout", entityType: "User", entityId: claims.sub, ipAddress: request.ip, correlationId: request.id }); return reply.code(204).send(); });
  app.get("/api/v1/me", async (request) => { const claims = await requireAuth(request); const result = await db().query("SELECT u.id,u.name,u.email,o.name organization_name FROM users u JOIN organizations o ON o.id=u.organization_id WHERE u.id=$1 AND u.organization_id=$2", [claims.sub, claims.organizationId]); return { user: { ...result.rows[0], roles: claims.roles } }; });
  app.get("/api/v1/organizations/:id", async (request, reply) => { const claims = await requireAuth(request); if ((request.params as { id: string }).id !== claims.organizationId) return reply.code(404).send({ message: "Organization not found" }); const result = await db().query("SELECT id,name,slug,timezone,created_at,updated_at FROM organizations WHERE id=$1", [claims.organizationId]); return result.rows[0]; });
  app.get("/api/v1/users", async (request) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR"]); const result = await db().query("SELECT u.id,u.name,u.email,u.status,array_agg(r.system_role) roles FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.organization_id=$1 GROUP BY u.id ORDER BY u.created_at", [claims.organizationId]); return { data: result.rows }; });
  app.post("/api/v1/users", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR"]); const body = createUserSchema.parse(request.body); const userId = randomUUID(); const role = await db().query("SELECT id FROM roles WHERE organization_id=$1 AND system_role=$2", [claims.organizationId, body.role]); if (!role.rows[0]) return reply.code(422).send({ message: "Role is unavailable" }); await db().query("INSERT INTO users (id,organization_id,name,email,password_hash,status) VALUES ($1,$2,$3,$4,$5,'ACTIVE')", [userId, claims.organizationId, body.name, body.email.toLowerCase(), await hashPassword(body.password)]); await db().query("INSERT INTO user_roles (user_id,role_id) VALUES ($1,$2)", [userId, role.rows[0].id]); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "user.created", entityType: "User", entityId: userId, newValue: { email: body.email, role: body.role }, ipAddress: request.ip, correlationId: request.id }); return reply.code(201).send({ id: userId, name: body.name, email: body.email, role: body.role }); });
  app.get("/api/v1/assets", async (request) => { const claims = await requireAuth(request); const result = await db().query("SELECT id,name,code,type,status,latitude,longitude,timezone,operator,description,metadata,created_at,updated_at FROM offshore_assets WHERE organization_id=$1 ORDER BY name", [claims.organizationId]); return { data: result.rows }; });
  app.post("/api/v1/assets", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR", "OPERATIONS_COORDINATOR"]); const body = assetSchema.parse(request.body); const id = randomUUID(); const result = await db().query("INSERT INTO offshore_assets (id,organization_id,name,code,type,status,latitude,longitude,timezone,operator,description,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id,name,code,type,status,latitude,longitude,timezone,operator,description,metadata,created_at,updated_at", [id, claims.organizationId, body.name, body.code, body.type, body.status, body.latitude, body.longitude, body.timezone, body.operator ?? null, body.description ?? null, body.metadata]); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "asset.created", entityType: "OffshoreAsset", entityId: id, newValue: body, ipAddress: request.ip, correlationId: request.id }); return reply.code(201).send(result.rows[0]); });
  app.get("/api/v1/assets/:id", async (request, reply) => { const claims = await requireAuth(request); const result = await db().query("SELECT id,name,code,type,status,latitude,longitude,timezone,operator,description,metadata,created_at,updated_at FROM offshore_assets WHERE id=$1 AND organization_id=$2", [(request.params as { id: string }).id, claims.organizationId]); return result.rows[0] ?? reply.code(404).send({ message: "Asset not found" }); });
  app.patch("/api/v1/assets/:id", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR", "OPERATIONS_COORDINATOR"]); const body = updateAssetSchema.parse(request.body); if (Object.keys(body).length === 0) return reply.code(400).send({ message: "At least one field is required" }); const id = (request.params as { id: string }).id; const previous = await db().query("SELECT id,name,code,type,status,latitude,longitude,timezone,operator,description,metadata FROM offshore_assets WHERE id=$1 AND organization_id=$2", [id, claims.organizationId]); if (!previous.rows[0]) return reply.code(404).send({ message: "Asset not found" }); const current = previous.rows[0] as Record<string, unknown>; const next = { ...current, ...body }; const result = await db().query("UPDATE offshore_assets SET name=$3,code=$4,type=$5,status=$6,latitude=$7,longitude=$8,timezone=$9,operator=$10,description=$11,metadata=$12,updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING id,name,code,type,status,latitude,longitude,timezone,operator,description,metadata,created_at,updated_at", [id, claims.organizationId, next.name, next.code, next.type, next.status, next.latitude, next.longitude, next.timezone, next.operator, next.description, next.metadata]); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "asset.updated", entityType: "OffshoreAsset", entityId: id, previousValue: current, newValue: body, ipAddress: request.ip, correlationId: request.id }); return result.rows[0]; });
  app.delete("/api/v1/assets/:id", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR"]); const id = (request.params as { id: string }).id; const result = await db().query("DELETE FROM offshore_assets WHERE id=$1 AND organization_id=$2 RETURNING id,name,code,type,status", [id, claims.organizationId]); if (!result.rows[0]) return reply.code(404).send({ message: "Asset not found" }); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "asset.deleted", entityType: "OffshoreAsset", entityId: id, previousValue: result.rows[0], ipAddress: request.ip, correlationId: request.id }); return reply.code(204).send(); });
  app.get("/api/v1/assets/:id/areas", async (request) => { const claims = await requireAuth(request); const result = await db().query("SELECT a.id,a.parent_id,a.name,a.code,a.type,a.description,a.created_at FROM asset_areas a JOIN offshore_assets o ON o.id=a.asset_id WHERE a.asset_id=$1 AND o.organization_id=$2 ORDER BY a.name", [(request.params as { id: string }).id, claims.organizationId]); return { data: result.rows }; });
  app.post("/api/v1/asset-areas", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR", "OPERATIONS_COORDINATOR"]); const body = assetAreaSchema.parse(request.body); const asset = await db().query("SELECT id FROM offshore_assets WHERE id=$1 AND organization_id=$2", [body.assetId, claims.organizationId]); if (!asset.rows[0]) return reply.code(404).send({ message: "Asset not found" }); if (body.parentId) { const parent = await db().query("SELECT id FROM asset_areas WHERE id=$1 AND asset_id=$2", [body.parentId, body.assetId]); if (!parent.rows[0]) return reply.code(422).send({ message: "Parent area is unavailable" }); } const id = randomUUID(); const result = await db().query("INSERT INTO asset_areas (id,asset_id,parent_id,name,code,type,description) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id,asset_id,parent_id,name,code,type,description,created_at", [id, body.assetId, body.parentId ?? null, body.name, body.code, body.type, body.description ?? null]); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "asset_area.created", entityType: "AssetArea", entityId: id, newValue: body, ipAddress: request.ip, correlationId: request.id }); return reply.code(201).send(result.rows[0]); });
  app.patch("/api/v1/asset-areas/:id", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR", "OPERATIONS_COORDINATOR"]); const body = updateAssetAreaSchema.parse(request.body); if (Object.keys(body).length === 0) return reply.code(400).send({ message: "At least one field is required" }); const id = (request.params as { id: string }).id; const previous = await db().query("SELECT a.id,a.asset_id,a.name,a.code,a.type,a.description FROM asset_areas a JOIN offshore_assets o ON o.id=a.asset_id WHERE a.id=$1 AND o.organization_id=$2", [id, claims.organizationId]); if (!previous.rows[0]) return reply.code(404).send({ message: "Asset area not found" }); const current = previous.rows[0] as Record<string, unknown>; const next = { ...current, ...body }; const result = await db().query("UPDATE asset_areas SET name=$2,code=$3,type=$4,description=$5 WHERE id=$1 RETURNING id,asset_id,parent_id,name,code,type,description,created_at", [id, next.name, next.code, next.type, next.description]); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "asset_area.updated", entityType: "AssetArea", entityId: id, previousValue: current, newValue: body, ipAddress: request.ip, correlationId: request.id }); return result.rows[0]; });
  app.delete("/api/v1/asset-areas/:id", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR"]); const id = (request.params as { id: string }).id; const area = await db().query("SELECT a.id,a.asset_id,a.name,a.code FROM asset_areas a JOIN offshore_assets o ON o.id=a.asset_id WHERE a.id=$1 AND o.organization_id=$2", [id, claims.organizationId]); if (!area.rows[0]) return reply.code(404).send({ message: "Asset area not found" }); const dependencies = await db().query("SELECT (SELECT count(*) FROM asset_areas WHERE parent_id=$1) + (SELECT count(*) FROM equipment WHERE area_id=$1) AS count", [id]); if (Number(dependencies.rows[0].count) > 0) return reply.code(409).send({ message: "Asset area still has dependent records" }); await db().query("DELETE FROM asset_areas WHERE id=$1", [id]); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "asset_area.deleted", entityType: "AssetArea", entityId: id, previousValue: area.rows[0], ipAddress: request.ip, correlationId: request.id }); return reply.code(204).send(); });
  app.get("/api/v1/assets/:id/equipment", async (request) => { const claims = await requireAuth(request); const result = await db().query("SELECT e.id,e.area_id,e.name,e.code,e.type,e.status,e.criticality,e.manufacturer,e.model,e.metadata,e.created_at,e.updated_at FROM equipment e JOIN offshore_assets o ON o.id=e.asset_id WHERE e.asset_id=$1 AND o.organization_id=$2 ORDER BY e.name", [(request.params as { id: string }).id, claims.organizationId]); return { data: result.rows }; });
  app.post("/api/v1/equipment", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR", "OPERATIONS_COORDINATOR"]); const body = equipmentSchema.parse(request.body); const asset = await db().query("SELECT id FROM offshore_assets WHERE id=$1 AND organization_id=$2", [body.assetId, claims.organizationId]); if (!asset.rows[0]) return reply.code(404).send({ message: "Asset not found" }); if (body.areaId) { const area = await db().query("SELECT id FROM asset_areas WHERE id=$1 AND asset_id=$2", [body.areaId, body.assetId]); if (!area.rows[0]) return reply.code(422).send({ message: "Area is unavailable" }); } const id = randomUUID(); const result = await db().query("INSERT INTO equipment (id,asset_id,area_id,name,code,type,status,criticality,manufacturer,model,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,asset_id,area_id,name,code,type,status,criticality,manufacturer,model,metadata,created_at,updated_at", [id, body.assetId, body.areaId ?? null, body.name, body.code, body.type, body.status, body.criticality, body.manufacturer ?? null, body.model ?? null, body.metadata]); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "equipment.created", entityType: "Equipment", entityId: id, newValue: body, ipAddress: request.ip, correlationId: request.id }); return reply.code(201).send(result.rows[0]); });
  app.patch("/api/v1/equipment/:id", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR", "OPERATIONS_COORDINATOR"]); const body = updateEquipmentSchema.parse(request.body); if (Object.keys(body).length === 0) return reply.code(400).send({ message: "At least one field is required" }); const id = (request.params as { id: string }).id; const previous = await db().query("SELECT e.id,e.name,e.code,e.type,e.status,e.criticality,e.manufacturer,e.model,e.metadata FROM equipment e JOIN offshore_assets o ON o.id=e.asset_id WHERE e.id=$1 AND o.organization_id=$2", [id, claims.organizationId]); if (!previous.rows[0]) return reply.code(404).send({ message: "Equipment not found" }); const current = previous.rows[0] as Record<string, unknown>; const next = { ...current, ...body }; const result = await db().query("UPDATE equipment SET name=$2,code=$3,type=$4,status=$5,criticality=$6,manufacturer=$7,model=$8,metadata=$9,updated_at=now() WHERE id=$1 RETURNING id,asset_id,area_id,name,code,type,status,criticality,manufacturer,model,metadata,created_at,updated_at", [id, next.name, next.code, next.type, next.status, next.criticality, next.manufacturer, next.model, next.metadata]); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "equipment.updated", entityType: "Equipment", entityId: id, previousValue: current, newValue: body, ipAddress: request.ip, correlationId: request.id }); return result.rows[0]; });
  app.delete("/api/v1/equipment/:id", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR"]); const id = (request.params as { id: string }).id; const result = await db().query("DELETE FROM equipment e USING offshore_assets o WHERE e.id=$1 AND e.asset_id=o.id AND o.organization_id=$2 RETURNING e.id,e.name,e.code,e.status", [id, claims.organizationId]); if (!result.rows[0]) return reply.code(404).send({ message: "Equipment not found" }); await audit({ organizationId: claims.organizationId, userId: claims.sub, action: "equipment.deleted", entityType: "Equipment", entityId: id, previousValue: result.rows[0], ipAddress: request.ip, correlationId: request.id }); return reply.code(204).send(); });
  app.get("/api/v1/audit", async (request) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR"]); const result = await db().query("SELECT id,action,entity_type,entity_id,created_at FROM audit_logs WHERE organization_id=$1 ORDER BY created_at DESC LIMIT 100", [claims.organizationId]); return { data: result.rows }; });
  app.setErrorHandler((error, _request, reply) => { if (error instanceof z.ZodError) return reply.code(400).send({ message: "Validation failed", issues: error.issues.map(({ path, message }) => ({ path, message })) }); const appError = error instanceof Error ? error : undefined; const status = (appError as (Error & { statusCode?: number }) | undefined)?.statusCode ?? 500; return reply.code(status).send({ message: status === 500 ? "Internal server error" : (appError?.message ?? "Request failed") }); });
  return app;
}
