import type { FastifyInstance } from "fastify";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { audit } from "./audit.js";
import { requireAuth, requireRole } from "./auth.js";
import { db } from "./database.js";

const vessel = z.object({ name: z.string().min(2).max(120), imo: z.string().regex(/^\d{7}$/).optional(), mmsi: z.string().regex(/^\d{9}$/).optional(), callsign: z.string().max(32).optional(), type: z.enum(["PSV","AHTS","OSRV","CSV","DSV","SURVEY","CREW_BOAT","TUG","SUPPLY","ACCOMMODATION","OTHER"]), flag: z.string().max(64).optional(), status: z.enum(["AVAILABLE","UNDERWAY","MOORED","MAINTENANCE","UNAVAILABLE"]).default("AVAILABLE"), capacity: z.number().int().nonnegative().optional(), operator: z.string().max(120).optional(), metadata: z.record(z.string(), z.unknown()).default({}) });
const position = z.object({ latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), speed: z.number().nonnegative().optional(), course: z.number().min(0).max(360).optional(), heading: z.number().min(0).max(360).optional(), navigationStatus: z.string().max(64).optional(), source: z.string().max(64).default("MANUAL"), accuracy: z.number().nonnegative().optional(), recordedAt: z.string().datetime().optional() });
const person = z.object({ name: z.string().min(2).max(120), employeeCode: z.string().regex(/^[A-Z0-9-]{2,32}$/), company: z.string().max(120).optional(), position: z.string().max(120).optional(), status: z.enum(["ACTIVE","INACTIVE","SUSPENDED"]).default("ACTIVE"), contact: z.record(z.string(), z.unknown()).default({}) });
const competency = z.object({ code: z.string().regex(/^[A-Z0-9-]{2,32}$/), name: z.string().min(2).max(120), description: z.string().max(4000).optional(), validityRequired: z.boolean().default(false) });
const pob = z.object({ personId: z.string().uuid(), assetId: z.string().uuid(), embarkedAt: z.string().datetime().optional(), expectedDisembarkAt: z.string().datetime().optional(), cabin: z.string().max(32).optional(), shift: z.string().max(32).optional() });

export function registerPhaseTwoRoutes(app: FastifyInstance) {
  app.get("/api/v1/vessels", async (request) => { const claims = await requireAuth(request); const result = await db().query("SELECT id,name,imo,mmsi,callsign,type,flag,status,capacity,operator,metadata,created_at,updated_at FROM vessels WHERE organization_id=$1 ORDER BY name", [claims.organizationId]); return { data: result.rows }; });
  app.post("/api/v1/vessels", async (request, reply) => { const claims = await requireAuth(request); requireRole(claims, ["ADMINISTRATOR", "OPERATIONS_COORDINATOR"]); const body = vessel.parse(request.body); const id=randomUUID(); const result=await db().query("INSERT INTO vessels (id,organization_id,name,imo,mmsi,callsign,type,flag,status,capacity,operator,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *", [id,claims.organizationId,body.name,body.imo??null,body.mmsi??null,body.callsign??null,body.type,body.flag??null,body.status,body.capacity??null,body.operator??null,body.metadata]); await audit({organizationId:claims.organizationId,userId:claims.sub,action:"vessel.created",entityType:"Vessel",entityId:id,newValue:body,ipAddress:request.ip,correlationId:request.id}); return reply.code(201).send(result.rows[0]); });
  app.patch("/api/v1/vessels/:id", async (request, reply) => { const claims=await requireAuth(request); requireRole(claims,["ADMINISTRATOR","OPERATIONS_COORDINATOR"]); const body=vessel.partial().parse(request.body); if(!Object.keys(body).length) return reply.code(400).send({message:"At least one field is required"}); const current=await db().query("SELECT * FROM vessels WHERE id=$1 AND organization_id=$2",[(request.params as {id:string}).id,claims.organizationId]); if(!current.rows[0]) return reply.code(404).send({message:"Vessel not found"}); const next={...current.rows[0],...body}; const result=await db().query("UPDATE vessels SET name=$3,imo=$4,mmsi=$5,callsign=$6,type=$7,flag=$8,status=$9,capacity=$10,operator=$11,metadata=$12,updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING *",[(request.params as {id:string}).id,claims.organizationId,next.name,next.imo,next.mmsi,next.callsign,next.type,next.flag,next.status,next.capacity,next.operator,next.metadata]); await audit({organizationId:claims.organizationId,userId:claims.sub,action:"vessel.updated",entityType:"Vessel",entityId:(request.params as {id:string}).id,previousValue:current.rows[0],newValue:body,ipAddress:request.ip,correlationId:request.id}); return result.rows[0]; });
  app.delete("/api/v1/vessels/:id", async (request, reply) => { const claims=await requireAuth(request); requireRole(claims,["ADMINISTRATOR"]); const result=await db().query("DELETE FROM vessels WHERE id=$1 AND organization_id=$2 RETURNING id,name",[(request.params as {id:string}).id,claims.organizationId]); if(!result.rows[0]) return reply.code(404).send({message:"Vessel not found"}); await audit({organizationId:claims.organizationId,userId:claims.sub,action:"vessel.deleted",entityType:"Vessel",entityId:result.rows[0].id,previousValue:result.rows[0],ipAddress:request.ip,correlationId:request.id}); return reply.code(204).send(); });
  app.get("/api/v1/vessels/:id/positions", async (request, reply) => { const claims=await requireAuth(request); const result=await db().query("SELECT p.* FROM vessel_positions p JOIN vessels v ON v.id=p.vessel_id WHERE p.vessel_id=$1 AND v.organization_id=$2 ORDER BY p.recorded_at DESC LIMIT 500",[(request.params as {id:string}).id,claims.organizationId]); if(!result.rows.length){const exists=await db().query("SELECT 1 FROM vessels WHERE id=$1 AND organization_id=$2",[(request.params as {id:string}).id,claims.organizationId]); if(!exists.rows[0]) return reply.code(404).send({message:"Vessel not found"});} return {data:result.rows}; });
  app.post("/api/v1/vessels/:id/positions", async (request, reply) => { const claims=await requireAuth(request); requireRole(claims,["ADMINISTRATOR","OPERATIONS_COORDINATOR"]); const body=position.parse(request.body); const vesselResult=await db().query("SELECT id FROM vessels WHERE id=$1 AND organization_id=$2",[(request.params as {id:string}).id,claims.organizationId]); if(!vesselResult.rows[0]) return reply.code(404).send({message:"Vessel not found"}); const id=randomUUID(); const result=await db().query("INSERT INTO vessel_positions (id,vessel_id,latitude,longitude,speed,course,heading,navigation_status,source,accuracy,recorded_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *",[id,(request.params as {id:string}).id,body.latitude,body.longitude,body.speed??null,body.course??null,body.heading??null,body.navigationStatus??null,body.source,body.accuracy??null,body.recordedAt??new Date().toISOString()]); await audit({organizationId:claims.organizationId,userId:claims.sub,action:"vessel.position_updated",entityType:"Vessel",entityId:(request.params as {id:string}).id,newValue:body,ipAddress:request.ip,correlationId:request.id}); return reply.code(201).send(result.rows[0]); });
  app.get("/api/v1/people", async (request) => {const claims=await requireAuth(request); const result=await db().query("SELECT * FROM people WHERE organization_id=$1 ORDER BY name",[claims.organizationId]); return {data:result.rows};});
  app.post("/api/v1/people", async (request, reply) => {const claims=await requireAuth(request); requireRole(claims,["ADMINISTRATOR","OPERATIONS_COORDINATOR"]); const body=person.parse(request.body); const id=randomUUID(); const result=await db().query("INSERT INTO people (id,organization_id,name,employee_code,company,position,status,contact) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",[id,claims.organizationId,body.name,body.employeeCode,body.company??null,body.position??null,body.status,body.contact]); await audit({organizationId:claims.organizationId,userId:claims.sub,action:"person.created",entityType:"Person",entityId:id,newValue:body,ipAddress:request.ip,correlationId:request.id}); return reply.code(201).send(result.rows[0]);});
  app.get("/api/v1/competencies", async (request)=>{const claims=await requireAuth(request); const result=await db().query("SELECT * FROM competencies WHERE organization_id=$1 ORDER BY name",[claims.organizationId]); return {data:result.rows};});
  app.post("/api/v1/competencies", async (request, reply)=>{const claims=await requireAuth(request); requireRole(claims,["ADMINISTRATOR"]); const body=competency.parse(request.body); const id=randomUUID(); const result=await db().query("INSERT INTO competencies (id,organization_id,code,name,description,validity_required) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *",[id,claims.organizationId,body.code,body.name,body.description??null,body.validityRequired]); await audit({organizationId:claims.organizationId,userId:claims.sub,action:"competency.created",entityType:"Competency",entityId:id,newValue:body,ipAddress:request.ip,correlationId:request.id}); return reply.code(201).send(result.rows[0]);});
  app.get("/api/v1/assets/:id/pob", async(request)=>{const claims=await requireAuth(request); const result=await db().query("SELECT p.id,p.name,p.employee_code,p.company,p.position,b.embarked_at,b.expected_disembark_at,b.cabin,b.shift FROM people_on_board b JOIN people p ON p.id=b.person_id JOIN offshore_assets a ON a.id=b.asset_id WHERE b.asset_id=$1 AND a.organization_id=$2 AND b.status='ON_BOARD' ORDER BY p.name",[(request.params as {id:string}).id,claims.organizationId]); return {data:result.rows};});
  app.post("/api/v1/pob", async(request,reply)=>{const claims=await requireAuth(request); requireRole(claims,["ADMINISTRATOR","OPERATIONS_COORDINATOR"]); const body=pob.parse(request.body); const valid=await db().query("SELECT p.id FROM people p JOIN offshore_assets a ON a.organization_id=p.organization_id WHERE p.id=$1 AND a.id=$2 AND p.organization_id=$3",[body.personId,body.assetId,claims.organizationId]); if(!valid.rows[0]) return reply.code(422).send({message:"Person or asset is unavailable"}); const id=randomUUID(); const result=await db().query("INSERT INTO people_on_board (id,person_id,asset_id,embarked_at,expected_disembark_at,status,cabin,shift) VALUES ($1,$2,$3,$4,$5,'ON_BOARD',$6,$7) RETURNING *",[id,body.personId,body.assetId,body.embarkedAt??new Date().toISOString(),body.expectedDisembarkAt??null,body.cabin??null,body.shift??null]); await audit({organizationId:claims.organizationId,userId:claims.sub,action:"person.embarked",entityType:"PersonOnBoard",entityId:id,newValue:body,ipAddress:request.ip,correlationId:request.id}); return reply.code(201).send(result.rows[0]);});
}
